movieproject/movieapp/urls.py
from django.urls import path, include
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.addMovie,name='addMovie'),
    path('update/<int:id>/',views.updateMovie,name='update'),
    path('delete/<int:id>/',views.deleteMovie,name='delete'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=50)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movie
class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from . forms import movieform
# Create your views here.
#show in homepage
def index(request):
    mv=movie.objects.all()
    context={
        'key1':mv
    }
    # return HttpResponse("Hello movieapp",context)
    return render(request,'index.html',context)

#show seperatley by id
def detail(requet,movie_id):
    # return HttpResponse("This movie %s" % movie_id)
    mv2=movie.objects.get(id=movie_id)
    return render(requet,'detail.html',{'key2':mv2})

#add to adminpannel from form
def addMovie(request):
    if request.method=='POST':
        name1=request.POST.get('name')
        desc2= request.POST.get('desc')
        year2= request.POST.get('year')
        img2= request.FILES['img']
        mv=movie(name=name1,desc=desc2,year=year2,img=img2)
        mv.save()
        return redirect('/')
    return render(request,'add.html')

#update function
def updateMovie(request,id):
    mv3=movie.objects.get(id=id)
    fm=movieform(request.POST or None,request.FILES,instance=mv3)
    if fm.is_valid():
        fm.save()
        return redirect('/')
    return render(request,'edit.html',{'fm':fm,'mv3':mv3})

def deleteMovie(request,id):
    if request.method== 'POST':
        mv4=movie.objects.get(id=id)
        mv4.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name"><br>
    <input type="text" name="desc" placeholder="Enter Movie Description"><br>
    <input type="text" name="year" placeholder="Enter Year of Release"><br>
    <input type="file" name="img"><br>
    <input type="submit"><br>
</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MovieApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" >
</head>
<body>
<!-- Image and text -->
<!--<nav class="navbar navbar-dark bg-dark">-->
<!--  <a class="navbar-brand" href="#">-->
<!--&lt;!&ndash;    <img src="/docs/4.6/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">&ndash;&gt;-->
<!--    Movie App-->
<!--  </a>-->
<!--    <a class="btn btn-warning" href="{% url 'movieapp:index'%}">Home</a>-->
<!--    <a class="btn btn-warning" href="{% url 'movieapp:addMovie'%}">Add Movie</a>-->
<!--</nav>-->
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Movie App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'movieapp:index'%}">Home</a>
        <a class="nav-link" href="{% url 'movieapp:addMovie'%}">Add Movie</a>
      </div>
    </div>
  </div>
</nav>
</body>
{% block body %}
{% endblock %}
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Do you want to delete this movie?<input type="submit">

</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
                <img src="{{key2.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <p>Name: {{key2.name}}</p><p>Detail:  {{key2.desc}}</p><p>Released on: {{key2.year}} </p><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' key2.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' key2.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
<!--    fm from views.py-->
    {{fm.as_p}}
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div>
    <div class="row">
        {% for i in key1 %}
        <div class="col-md-3" style="padding:5px;">
            <div class="card" style="width:150">
                <img src="{{i.img.url}}" class="card-img-top" alt="..." width="250" height="250">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
<!--                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View More</a>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}
<!--<br>-->
<!--{{i.name}} , {{i.desc}} , {{i.year}}. <br>-->
<!--<a href="movie/{{i.id}}">{{i.name}} , {{i.desc}} , {{i.year}}.<br></a>-->
<!--<img src="{{i.img.url}}" width="150" height="150">-->
<!--<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br></a>-->